### ISSUE TITLE
maven support

### ISSUE THREAD

**Issue by medvedutka** [pgdurand/jGAF#1]
Would it be possible to upload releases on public maven repository? Doing so, it will be way easier to reuse the library.

Thank you for your work on this project.

**Comment by pgdurand** [comment]
I think that could be possible... however, as far as I know, a Maven project has a dedicated  directory structure that does not fit jGAF actual one. I would prefer not to change everything. Could you provide me with some help to see how I could slightly (1) prepare a Maven package for jGAF, (2) upload it to a public Maven Repo and (3) tell me which public Maven Repo should I use ?

**Comment by krichter722** [comment]
I'm providing a draft at https://github.com/krichter722/jGAF/tree/maven based on what I think has been intended with `ant`. There're some parts of the build process missing, e.g. creation of Android artifacts afaik.

Regarding your questions: I'm referring you to the available documentation since it's much better than any summary anyone could reproduce here:
(1) There's no way around making yourself familiar with the [directory structure of Maven](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) as well as the lifecycle and [plugins](https://maven.apache.org/guides/introduction/introduction-to-plugins.html). It seems odd at first, but you'll learn to love it :)
(2) Deployment through [OSSRH](https://central.sonatype.org/pages/ossrh-guide.html) (a possibility to deploy FLOSS software) is really neat and an investment of 5 to 10 hours allows to configure continuous deployment with a free CI service (which is beyond the scope of Maven migration, but should be done as well if you're starting such a large change).

**Comment by zlay0701** [comment]
can you upload the maven version to "https://jitpack.io/" ??  just like maven repo

**Comment by zlay0701** [comment]
https://jitpack.io/ is always free for open-source

**Comment by DrDaleks** [comment]
> can you upload the maven version to "https://jitpack.io/" ?? just like maven repo

@zlay0701 FYI I forked the project to make it jitpick-compatible (see #3), so you can use that while the pull request is being reviewed.

EDIT: I believe I spoke too soon, the jitpack artefact isn't there :(
EDIT #2: all works now, tags just weren't in sync => you'll need to point to `v2.4.0-jitpack` for the time being.
